CREATE DATABASE IF NOT EXISTS `TESSIER` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `TESSIER`;

CREATE TABLE `PERSONNEL` (
  `idperso` VARCHAR(42),
  `mail` VARCHAR(42),
  `mdp` VARCHAR(42),
  `nom` VARCHAR(42),
  `prénom` VARCHAR(42),
  PRIMARY KEY (`idperso`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ENVOYÉ` (
  `pdf` VARCHAR(42),
  `idperso` VARCHAR(42),
  `iddate` VARCHAR(42),
  PRIMARY KEY (`pdf`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*
CREATE TABLE `DATE` (
  `iddate` VARCHAR(42),
  PRIMARY KEY (`iddate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
*/

-- ALTER TABLE `ENVOYÉ` ADD FOREIGN KEY (`iddate`) REFERENCES `DATE` (`iddate`);
ALTER TABLE `ENVOYÉ` ADD FOREIGN KEY (`idperso`) REFERENCES `PERSONNEL` (`idperso`);