CREATE DATABASE IF NOT EXISTS `TESSIER` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `TESSIER`;

CREATE TABLE `PERSONNEL` (
  `idperso` VARCHAR(42),
  `mail` VARCHAR(42),
  `mdp` VARCHAR(42),
  `nom` VARCHAR(42),
  `prénom` VARCHAR(42),
  `admin(o/n)` VARCHAR(42),
  PRIMARY KEY (`idperso`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `EXERCER` (
  `idperso` VARCHAR(42),
  `idstatut` VARCHAR(42),
  PRIMARY KEY (`idperso`, `idstatut`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ENVOYÉ` (
  `pdf` VARCHAR(42),
  `idperso` VARCHAR(42),
  `mois` VARCHAR(42),
  PRIMARY KEY (`pdf`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ÊTREACTIF` (
  `mois` VARCHAR(42),
  `idperso` VARCHAR(42),
  PRIMARY KEY (`mois`, `idperso`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `STATUT` (
  `idstatut` VARCHAR(42),
  `libellé` VARCHAR(42),
  PRIMARY KEY (`idstatut`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `MOIS` (
  `mois` VARCHAR(42),
  `année` VARCHAR(42),
  PRIMARY KEY (`mois`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*
CREATE TABLE `ANNÉE` (
  `année` VARCHAR(42),
  PRIMARY KEY (`année`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
*/

ALTER TABLE `EXERCER` ADD FOREIGN KEY (`idstatut`) REFERENCES `STATUT` (`idstatut`);
ALTER TABLE `EXERCER` ADD FOREIGN KEY (`idperso`) REFERENCES `PERSONNEL` (`idperso`);
ALTER TABLE `ENVOYÉ` ADD FOREIGN KEY (`mois`) REFERENCES `MOIS` (`mois`);
ALTER TABLE `ENVOYÉ` ADD FOREIGN KEY (`idperso`) REFERENCES `PERSONNEL` (`idperso`);
ALTER TABLE `ÊTREACTIF` ADD FOREIGN KEY (`idperso`) REFERENCES `PERSONNEL` (`idperso`);
ALTER TABLE `ÊTREACTIF` ADD FOREIGN KEY (`mois`) REFERENCES `MOIS` (`mois`);
-- ALTER TABLE `MOIS` ADD FOREIGN KEY (`année`) REFERENCES `ANNÉE` (`année`);